### ISSUE TITLE
Can't use the extension

### ISSUE THREAD

**Issue by vonsogt** [laravel-admin-extensions/lodpod-editor#1]
I got this error

`[InvalidArgumentException]                                                                                                                                             
  Could not find a matching version of package laravel-admin-ext/lodpod-editor. Check the package spelling, your version constraint and that the package is available    
  in a stability which matches your minimum-stability (dev).`

**Comment by williamtse** [comment]
use `composer require xiewenfeng/lodpod-editor`

**Comment by vonsogt** [comment]
> use `composer require xiewenfeng/lodpod-editor`

It worked
